const { spawn } = require('child_process');
const helper = 'C:\Users\Admin\.dsh\profiles\web-test\node_modules\dsh-web-open\assets\dsh-tray-helper.ps1'.replace(/\\/g, '/');
const ico = 'C:\Users\Admin\.dsh\profiles\web-test\node_modules\dsh-web-open\assets\dsh.ico'.replace(/\\/g, '/');
const c = spawn('powershell.exe', ['-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',helper,'-HostPid','8316','-Url','http://127.0.0.1:9999','-IconPath',ico,'-LogFile','C:/CodeSpace/dsh-web-open/helper-debug3.log'], { stdio: ['ignore','pipe','pipe'], detached: true, windowsHide: true });
let out = '', err = '';
c.stdout.on('data', d => out += d);
c.stderr.on('data', d => err += d);
c.on('error', e => console.error('SPAWN ERROR:', e.message));
c.on('exit', (code, sig) => { console.log('EXIT code=' + code + ' sig=' + sig); console.log('STDOUT: ' + out.slice(0,500)); console.log('STDERR: ' + err.slice(0,500)); });
console.log('spawned pid:', c.pid);
setTimeout(() => { console.log('--- after 5s: still waiting, helper pid alive?'); }, 5000);