# dsh-tray-helper.ps1 - Windows tray helper launched by the dsh-web-open plugin.
# Shows a whale tray icon with a right-click menu, watches the host dsh web
# process, and exits when the host exits. Optionally hides the host console
# window and creates a desktop shortcut.
[CmdletBinding()]
param(
  [Parameter(Mandatory)][int]$HostPid,
  [Parameter(Mandatory)][string]$Url,
  [Parameter(Mandatory)][string]$IconPath,
  [switch]$HideConsole,
  [switch]$CreateShortcut,
  [string]$LogFile = ''
)

$ErrorActionPreference = 'SilentlyContinue'

function Write-Log([string]$msg) {
  if ($LogFile) { try {
    $dir = Split-Path $LogFile -Parent
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    Add-Content -Path $LogFile -Value ("[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $msg) -Encoding UTF8
  } catch {} }
}

# Hide the host console window (attach to its console, hide the window).
if ($HideConsole) {
  try {
    Add-Type -Namespace DshTray -Name Console -MemberDefinition @'
[DllImport("kernel32.dll")] public static extern bool AttachConsole(int pid);
[DllImport("kernel32.dll")] public static extern bool FreeConsole();
[DllImport("kernel32.dll")] public static extern IntPtr GetConsoleWindow();
[DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr h, int n);
'@
    [DshTray.Console]::AttachConsole($HostPid) | Out-Null
    $hwnd = [DshTray.Console]::GetConsoleWindow()
    if ($hwnd -ne [IntPtr]::Zero) { [DshTray.Console]::ShowWindow($hwnd, 0) | Out-Null }
    [DshTray.Console]::FreeConsole() | Out-Null
    Write-Log 'host console hidden'
  } catch { Write-Log ("hide console failed: " + $_.Exception.Message) }
}

# Create the desktop shortcut once (points at wscript + a hidden launch VBS).
if ($CreateShortcut) {
  try {
    $ws = New-Object -ComObject WScript.Shell
    $desktop = [Environment]::GetFolderPath('Desktop')
    $lnk = Join-Path $desktop 'DSH Web.lnk'
    if (-not (Test-Path $lnk)) {
      $vbsDir = Join-Path $env:LOCALAPPDATA 'dsh-web-open'
      New-Item -ItemType Directory -Force -Path $vbsDir | Out-Null
      $ps1 = Join-Path $vbsDir 'launch.ps1'
      $ps1Content = @'
# Smart launcher generated by dsh-web-open: if the dsh web server is already
# listening, just open the browser; otherwise start it hidden.
$Port = 3080
$Url = "http://127.0.0.1:$Port"
$up = $false
try {
  $c = New-Object Net.Sockets.TcpClient
  $c.Connect('127.0.0.1', $Port)
  $c.Close()
  $up = $true
} catch {}
if ($up) {
  Start-Process $Url
} else {
  Start-Process -FilePath 'cmd.exe' -ArgumentList @('/c', 'dsh web') -WindowStyle Hidden
}
'@
      [IO.File]::WriteAllText($ps1, $ps1Content, (New-Object System.Text.UTF8Encoding($false)))
      $vbs = Join-Path $vbsDir 'launch.vbs'
      $vbsContent = 'Set sh = CreateObject("WScript.Shell")' + [char]13 + [char]10
      $vbsContent += 'sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""' + $ps1 + '""", 0, False' + [char]13 + [char]10
      [IO.File]::WriteAllText($vbs, $vbsContent, (New-Object System.Text.ASCIIEncoding))
      $sc = $ws.CreateShortcut($lnk)
      $sc.TargetPath = "$env:WINDIR\System32\wscript.exe"
      $sc.Arguments = '"' + $vbs + '"'
      $sc.IconLocation = $IconPath + ',0'
      $sc.Description = 'DSH Web - DeepSeek Harness Web UI'
      $sc.Save()
      Write-Log ("desktop shortcut created: " + $lnk)
    }
  } catch { Write-Log ("shortcut failed: " + $_.Exception.Message) }
}

# Single instance: when another tray helper is already running, just open the browser.
$mutex = New-Object System.Threading.Mutex($false, 'DSHWebOpenTray')
if (-not $mutex.WaitOne(0)) {
  try { Start-Process $Url } catch {}
  exit 0
}

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$script:notify = $null
$script:ctx = $null

$icon = New-Object System.Drawing.Icon($IconPath)
$script:notify = New-Object System.Windows.Forms.NotifyIcon
$notify.Icon = $icon
$notify.Text = 'DSH Web'
$notify.Visible = $true

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$miOpen = New-Object System.Windows.Forms.ToolStripMenuItem
$miOpen.Text = '打开浏览器'
$miOpen.Add_Click({ try { Start-Process $Url } catch {} })
$menu.Items.Add($miOpen) | Out-Null
$miRestart = New-Object System.Windows.Forms.ToolStripMenuItem
$miRestart.Text = '重启服务'
$miRestart.Add_Click({
  try { & taskkill /PID $HostPid /T /F 2>$null | Out-Null } catch {}
  Start-Sleep -Milliseconds 500
  try { Start-Process -FilePath 'powershell.exe' -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-Command','dsh web') -WindowStyle Hidden } catch {}
})
$menu.Items.Add($miRestart) | Out-Null
$menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator)) | Out-Null
$miStop = New-Object System.Windows.Forms.ToolStripMenuItem
$miStop.Text = '停止服务并退出'
$miStop.Add_Click({
  try { & taskkill /PID $HostPid /T /F 2>$null | Out-Null } catch {}
  try { $script:notify.Visible = $false; $script:notify.Dispose() } catch {}
  try { if ($script:ctx) { $script:ctx.ExitThread() } } catch {}
})
$menu.Items.Add($miStop) | Out-Null
$notify.ContextMenuStrip = $menu
$notify.Add_DoubleClick({ try { Start-Process $Url } catch {} })

Write-Log ("tray up for host " + $HostPid + " at " + $Url)

# Watch the host process; exit when it is gone.
$watch = New-Object System.Windows.Forms.Timer
$watch.Interval = 2000
$watch.Add_Tick({
  $alive = Get-Process -Id $HostPid -ErrorAction SilentlyContinue
  if (-not $alive) {
    $watch.Stop()
    try { $script:notify.Visible = $false; $script:notify.Dispose() } catch {}
    try { if ($script:ctx) { $script:ctx.ExitThread() } } catch {}
  }
})
$watch.Start()

$script:ctx = New-Object System.Windows.Forms.ApplicationContext
[System.Windows.Forms.Application]::Run($script:ctx)

try { $script:notify.Visible = $false; $script:notify.Dispose() } catch {}
try { $icon.Dispose() } catch {}
try { $menu.Dispose() } catch {}
try { $mutex.ReleaseMutex(); $mutex.Dispose() } catch {}
Write-Log 'tray helper exited'
exit 0
